spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/web/
    suffix: .html
    content-type: text/html
  mvc:
   view:
    prefix: /jsp
    suffix: .jsp
eureka:
  instance:
    prefer-ip-address: true
    hostname: feignserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://aa:abcd@localhost:8761/eureka/
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
ribbon:
  eureka:
    enabled: true
feign:
  httpclient:
    enabled: true
  hystrix:
   enabled: true
bootcwenao:
  kafka:
    binder:
      brokers: 127.0.0.1:9092
      zk-nodes: 127.0.0.1:2181
    group: cwenao-group